language: java
env:
  global:
  - secure: OvZr50fpO4/RZAUnL7EcGZ5bWNRrIcEWA57xv7f6fM4Ctb4eZ344iXSry+QUKcuqwuqADmyHlDKb9xOIFpkIfElkXG+5Ktj0qv75Mm+k0ogD+Zpy455o1TrV8ofNV1sSgDRAVrAC3vBApHCochf9ji3RadyMQPWarwfxeVQ4PoY=
  - secure: IIQPyZhE9pY4IPQxMs6Eq3ziwYzYvRmDU331qduz/7G1Gip7b5zzJ7B+mBCZ9/2EtkWmf6OXTrrBoX45mKLmXvYsxCnPgm5lAq+iDLA3/urZt5akz/jeoQzudnOb/9E6Zr7HVPYbEYePNgUumVjaqxnEwBfruQ5Y7GrAiEKTxxk=
  - secure: uYndWoQe4VpCe8nYtSAXHeUcVmDN5UfGBpreDy6PDFZcM3fKaX5+2KaVuaC1gz03hxl4BeK0ea0v0x8hQqaP8zjMufp6ex5oiY+Bn4PInfnzhEwkpc2Kgkv4W/h5ljILwgVLP4TQFP/xQUH6Lm0qWUxBQyaAjz0OXxz13O54vlc=
  - secure: Qrff4qhxw3I95ZC+0Rbw7Jx1cr5rKcSwnhpBkiS5GBGJNIgXDwmGChODHhW7CxmeZrEhG9kVub1RR4XKa5U7D6dFSE6i1C0NVxlRfgukBKV2hW3vKSqn/BvWtCHw5pLjRPIUBA93SecKW+qWmDNwqI87KDH7VZgXd69c5lkCLxA=
  - secure: p9nxB7SU5Pgu2g8VwRoztq9H9PIzd7GYA1B37p384l+4C7BKCtPVJyf2g+MdJ3ir28euE0pbHwjZm2rk35Yd5JdUzmlWnMOpS8tg6tXv4OgKlFKLYlAwuLar7surFAoSFeyr8eLzv1nCstPvwc6FmdeHzmPkdZEDT4JZTgA1kzc=
